repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check
        language: system
        types_or: [python, pyi]
        pass_filenames: true

      - id: bandit
        name: bandit
        entry: uv run bandit -q
        language: system
        types: [python]
        exclude: ^tests/
        pass_filenames: true

      - id: detect-secrets
        name: detect secrets
        entry: uv run detect-secrets-hook --baseline .secrets.baseline
        language: system
        pass_filenames: true
